
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      compiler: g++
      language: cpp
      sudo: required
      dist: trusty
      before_install:
      - sudo dpkg --add-architecture i386
      - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      - sudo apt-get update
      - sudo apt-get install -y -f build-essential software-properties-common g++-5-multilib gcc-5-multilib libc6-dev libc6-dev:i386 libssl-dev libssl-dev:i386

      script:
      - make linux32 CXX=g++-5
      - make linux64 CXX=g++-5
